### ISSUE TITLE
xai_analysis metric component output interpretation

### ISSUE THREAD

**Issue by elmokhtar-mohamedmoussa-idnow** [mammoth-eu/mammoth-commons#9]
Hi,
I had a question about how to read/interpret the output of the xai_analysis component.
When I tested it with the integration test in `tests/test_tc6_facex.py` I had several pop ups, some of them I couldn't understand  (for instance the figure 1 with the three subplots) and some looked familiar like activation map of face region (figure 17) but I still can't interpret. 
I suggest to have also a text output providing an annotation and explanation of the plots.
 
![image](https://github.com/user-attachments/assets/7900fafe-56a4-45fa-9b4b-f8d7e144569d)

Also, the test code return an error at https://github.com/mammoth-eu/mammoth-commons/blob/dev/tests/test_tc6_facex.py#L37

Thank a lot in advance, 
Mokhtar.

**Comment by maniospas** [comment]
Hello, I will handle the error: can you upload here the full stack trace?
@gsarridis I imagine the actual issue is that pop-ups are intermediate computations, and one should view the shown html (that fails in @elmokhtar-mohamedmoussa-idnow 's case) for full clarity?

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
Here is the full stack trace : 
`
> python -m tests.test_tc6_facex 
/home/elmokhtarmohamedmoussa/Desktop/mammoth-commons/catalogue/model_loaders/pytorch.py:32: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(state_path))
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.17s/it]
WARNING:matplotlib.image:Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/home/elmokhtarmohamedmoussa/miniconda3/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elmokhtarmohamedmoussa/miniconda3/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/elmokhtarmohamedmoussa/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/elmokhtarmohamedmoussa/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/elmokhtarmohamedmoussa/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/elmokhtarmohamedmoussa/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elmokhtarmohamedmoussa/.vscode/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/elmokhtarmohamedmoussa/Desktop/mammoth-commons/tests/test_tc6_facex.py", line 40, in <module>
    test_facex()
  File "/home/elmokhtarmohamedmoussa/Desktop/mammoth-commons/tests/test_tc6_facex.py", line 37, in test_facex
    markdown_result.show()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'show'`

**Comment by maniospas** [comment]
This suggests an internal commons bug indeed. I think I fixed something similar at some point, so can you pull the latest version and try again?

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
Hi, I pulled the latest version I still have the same issue.

**Comment by maniospas** [comment]
Hi, thanks for trying. I finally managed to replicate the exact reported bug and fixed it within pull request #12 . If you again pull the latest version of the code it should be working.

If it does work, please close this issue and create a separate one for further requests on improved interpretation.

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
Thanks its working now !
